// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnZcXGnt1szQ9SFE2IyFQBNK16WLfx0c4',
    appId: '1:130755868175:web:78a197411557c8e288d57a',
    messagingSenderId: '130755868175',
    projectId: 'task-manager-2f518',
    authDomain: 'task-manager-2f518.firebaseapp.com',
    storageBucket: 'task-manager-2f518.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf1EEGIfDlrwmaMlmy0x9qd5T3Pch6nLg',
    appId: '1:130755868175:ios:faf8c1e6fe7d0c1c88d57a',
    messagingSenderId: '130755868175',
    projectId: 'task-manager-2f518',
    storageBucket: 'task-manager-2f518.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf1EEGIfDlrwmaMlmy0x9qd5T3Pch6nLg',
    appId: '1:130755868175:ios:faf8c1e6fe7d0c1c88d57a',
    messagingSenderId: '130755868175',
    projectId: 'task-manager-2f518',
    storageBucket: 'task-manager-2f518.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnZcXGnt1szQ9SFE2IyFQBNK16WLfx0c4',
    appId: '1:130755868175:web:768920fc9879aed988d57a',
    messagingSenderId: '130755868175',
    projectId: 'task-manager-2f518',
    authDomain: 'task-manager-2f518.firebaseapp.com',
    storageBucket: 'task-manager-2f518.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Rs4lM0cJ0vtMMrRyq30wuOVXieyM4hA',
    appId: '1:130755868175:android:6586d502165fa51088d57a',
    messagingSenderId: '130755868175',
    projectId: 'task-manager-2f518',
    storageBucket: 'task-manager-2f518.firebasestorage.app',
  );

}